gcpCredentials:
    projectId: cloudlab_rso
    topicPath: projects/cloudlab-rso/topics/topic-w
    subscriptionPath: "projects/cloudlab-rso/subscriptions/sub_w"
    credentialsPath: "./pubsub-sa.json"
messageParameters:
    numberOfMessages: 15
    messageLengthX: 1
messageArgs:
    origin: python-sample
    username: gcp
batch: False
batchSettings:
    maxMessages: 100
    maxBytes: 1024
    maxLatency: 1
